template = "https://github.com/giellalt/template-lang-und"
rev_id = 295
template_sha = "9e160f410d669a53f8b740a218fd6462f17d3234"

[replacements]
__GLOTTOLOG_ID__ = "selk1253"
__REPO__ = "lang-sel"
__UND2C__ = "sel"
__UNDEFINED__ = "Selkup"
__UND__ = "sel"
