template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "2ae3f964876faa6636309f7d609478512097ebd0"

[replacements]
__GLOTTOLOG_ID__ = "selk1253"
__REPO__ = "lang-sel"
__UND2C__ = "sel"
__UNDEFINED__ = "Selkup"
__UND__ = "sel"
