template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "selk1253"
__REPO__ = "lang-sel"
__UND2C__ = "sel"
__UNDEFINED__ = "Selkup"
__UND__ = "sel"
