[package]
name = "sel"
human_name = "Selkup"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.sel]
filename = "sel-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-sel"
platform = "windows"
uuid = "BFFD8709-CD82-4084-A202-E19619582217"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.sel"
package = "speller-sel"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-sel-mso"
platform = "windows"
uuid = "E82D3310-C767-44EF-802B-90842D315F57"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-sel"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
